events {}

http{
    upstream fastapi{
        server app:8000;
    }
    upstream mlflow{
        server mlflow:5000;
    }

server{
    listen 80;
    server_name app.aravindhmlsystems.uk;
    location /{
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
server{
    listen 80;
    server_name mlflow.aravindhmlsystems.uk;
    location /{
        proxy_pass http://mlflow;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
}