event{}

http{
    upstream fastapi{
        server api:8000;
    }
    upstream mlflow{
        server mlflow:5000;
    }

server{
    listen 80;
    location /api/{
        proxy_pass http://fastapi;
    }
    location /mlflow/{
        proxy_pass http://mlflow;
    }
}
}