services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: postgres_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mlflow:
    image: 564445391819.dkr.ecr.ap-south-2.amazonaws.com/mlops-mlflow
    container_name: mlflow
    depends_on:
      postgres: 
        condition: service_healthy
    restart: unless-stopped
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://mlflow:mlflow@postgres:5432/postgres_data
      --default-artifact-root s3://mlops-artifacts-aravindh-ml/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts '*'
      --cors-allowed-origins "https://mlflow.aravindhmlsystems.uk"
    environment:
      DB_URI: postgresql+psycopg2://mlflow:mlflow@postgres:5432/postgres_data
      ARTIFACT_URI: s3://mlops-artifacts-aravindh-ml/artifacts
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000').raise_for_status()"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  app:
    image: 564445391819.dkr.ecr.ap-south-2.amazonaws.com/mlops-app
    container_name: app
    depends_on:
      mlflow: 
        condition: service_healthy
    restart: unless-stopped
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      ENVIRONMENT: Production
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/').raise_for_status()"]
      interval: 20s
      retries: 10
      start_period: 60s
  training:
    image: 564445391819.dkr.ecr.ap-south-2.amazonaws.com/mlops-training
    container_name: train_pipeline
    profiles:
      - training
    depends_on:
      mlflow:
        condition: service_healthy
    command: >
      sh -c "
      python train.py
      "
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      ENVIRONMENT: Production
      DATA_PATH: s3://mlops-artifacts-aravindh-ml/data/hour.csv
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/mlops/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      app:
        condition: service_healthy
      mlflow:
        condition: service_healthy

volumes:
  postgres_data:
  


  