events {}

http{
    upstream fastapi{
        server app:8000;
    }
    upstream mlflow{
        server mlflow:5000;
    }

server {
    listen 80;
    server_name app.aravindhmlsystems.uk;

    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name mlflow.aravindhmlsystems.uk;

    return 301 https://$host$request_uri;
}

server{
    listen 443 ssl;
    server_name app.aravindhmlsystems.uk;
    ssl_certificate /etc/letsencrypt/live/app.aravindhmlsystems.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.aravindhmlsystems.uk/privkey.pem;
    location /{
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
server{
    listen 443 ssl;
    server_name mlflow.aravindhmlsystems.uk;
    ssl_certificate /etc/letsencrypt/live/mlflow.aravindhmlsystems.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mlflow.aravindhmlsystems.uk/privkey.pem;
    location /{
        proxy_pass http://mlflow;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

    }
}
}