name: ML API CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Run integration tests
        run: docker compose -f docker-compose-test.yml up --build --exit-code-from test

      - name: Show logs (on failure)
        if: always()
        run: docker compose -f docker-compose-test.yml logs --tail=200

      - name: Show container status
        if: always()
        run: docker compose -f docker-compose-test.yml ps -a

      - name: Show exited containers
        if: always()
        run: docker ps -a
      
      - name: Show init_data logs
        if: always()
        run: docker logs init_data
      
      - name: Show mlflow logs
        if: always()
        run: docker logs mlflow

      - name: Show training logs
        if: always()
        run: docker logs train_pipeline
      
      - name: Show app logs
        if: always()
        run: docker logs app

      - name: Show tests logs
        if: always()
        run: docker logs tests
